server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/breed?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1598741
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
    enabled: true #开启文件上传
    max-file-size: 10MB #限制文件上传大小为10M
  # 初始化物理连接个数
  initial-size: 1
  # 最大连接池数量
  max-active: 20
  # 最小连接池数量
  min-idle: 5
  # 获取连接时最大等待时间(ms)
  max-wait: 60000
  # 开启缓存preparedStatement(PSCache)
  pool-prepared-statements: true
  # 启用PSCache后，指定每个连接上PSCache的大小
  max-pool-prepared-statement-per-connection-size: 20
  # 用来检测连接是否有效的sql
  validation-query: select 'x'
  # 申请连接时不检测连接是否有效
  test-on-borrow: false
  # 归还连接时不检测连接是否有效
  test-on-return: false
  # 申请连接时检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效（不影响性能）
  test-while-idle: true
  # 检测连接的间隔时间，若连接空闲时间 >= minEvictableIdleTimeMillis，则关闭物理连接
  time-between-eviction-runs-millis: 60000
  # 连接保持空闲而不被驱逐的最小时间(ms)
  min-evictable-idle-time-millis: 300000
  # 配置监控统计拦截的filters（不配置则监控界面sql无法统计），监控统计filter:stat，日志filter:log4j，防御sql注入filter:wall
  filters: stat,log4j,wall
  # 支持合并多个DruidDataSource的监控数据
  use-global-data-source-stat: true
  # 通过connectProperties属性来打开mergeSql(Sql合并)功能；慢SQL记录(配置超过5秒就是慢，默认是3秒)
  connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口

    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 30000ms # 连接超时时间（毫秒）
    key:
      admin: 'ums:admin'
      resourceList: 'ums:resourceList'
    expire:
      common: 86400 # 24小时
  mail:

    host: smtp.qq.com #这里换成自己的邮箱类型 例如qq邮箱就写smtp.qq.com
    username: 412741226@qq.com #QQ邮箱
    password: gtjysdjqnydxbhgb #邮箱密码或者授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true #开启SSL
    default-encoding: utf-8
    freemarker:
      cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
      suffix: .html # 模版后缀名 默认为ftl
      charset: UTF-8 # 文件编码
      template-loader-path: classpath:/templates/


mybatis:
  configuration:
    map-underscore-to-camel-case=true
  mapper-locations:
    - classpath*: /mapper/*.xml

logging:
  level:
    com.breed.govern.mapper: debug

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /ums-admin/login
      - /ums-admin/register
      - /ums-admin/info
      - /ums-admin/logout
      - /ums-admin/upload
      - /minio/upload

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: breed-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: 0
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

# MinIO对象存储相关配置
minio:
  endpoint: http://localhost:9000 #MinIO服务所在地址
  bucketName: jykj #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥

excel:
  fileName: "D:\\excel\\"



